on:
  workflow_dispatch:

name: Call Action Wlc

jobs:
  call-action-wlc:
    runs-on: ubuntu-latest

    steps:
      - uses: jasp-stats/jasp-actions/testwlc@master
        env:
          WEBLATE_KEY: ${{ secrets.WEBLATE_KEY }}
          QML_REPO: jasptestmodule-qml
          R_REPO: jasptestmodule-r
 
