name: test-wlc

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: macos-latest

    steps:
      - name: Install wlc
        run: pip3 install wlc
        shell: bash
        
      - name: Lock jasptestmodule
        run: wlc --key ${{ secrets.WEBLATE_KEY }} --url https://hosted.weblate.org/api/ lock jasp/jasptestmodule-r
        shell: bash
